version: 2
## NOTE: dropped all the non_null tests bc too many were failing
## at some point should more carefully add dq tests back
models:
  - name: stg_addresses
    description: Contains addresses of each user
    columns:
      - name: address_id
      - name: address
      - name: zipcode
      - name: state
      - name: country

  - name: stg_events
    description: Contains event information for greenery
    columns:
      - name: event_id
      - name: session_id
      - name: user_id
      - name: event_type
      - name: page_url
      - name: created_at
      - name: order_id
      - name: product_id

  - name: stg_order_items
    description: Contains product id, qty for each order
    columns:
      - name: order_id
      - name: product_id
      - name: quantity

  - name: stg_orders
    description: Contains information about each order placed
    columns:
      - name: order_id
      - name: promo_id
      - name: user_id
      - name: address_id
      - name: created_at
      - name: order_cost
      - name: shipping_cost
      - name: order_total
      - name: tracking_id
      - name: shipping_service
      - name: estimated_delivery_at
      - name: delivered_at
      - name: status

  - name: stg_products
    description: Contains product information 
    columns:
      - name: product_id
      - name: name
      - name: price
      - name: inventory

  - name: stg_promos
    description: Contains promotion information
    columns:
      - name: promo_id
      - name: discount
      - name: status

  - name: stg_users
    description: Contains contact information about each user
    columns:
      - name: user_id
      - name: first_name
      - name: last_name
      - name: email
      - name: phone_number
      - name: created_at
      - name: updated_at
      - name: address_id
